FROM golang:1.21-alpine AS builder
RUN apk add --no-cache git make bash curl
RUN git clone https://github.com/tendermint/tendermint.git && \
    cd tendermint && git checkout v0.34.24 && make build

FROM alpine:3.18
RUN apk add --no-cache bash
COPY --from=builder /go/tendermint/build/tendermint /usr/bin/tendermint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
